from Solver_better import SudokuSolver
import tkinter as tk
import multiprocessing
import time

# WARNING - This code is compatible only with backend Solver_2.py (and it´s versions)
#                       Warning:
#
# Most of this code was generated by AI. (mostly the multiprocessing mechanism)
# Credit: Gemini 2.5
#
# Ai code is always labeled

def reset(sudokug_list, core_labels):
    for radek in sudokug_list:
        for e in radek:
            e.delete(0, tk.END)
            e.config(fg="black")
    # Reset dashboardu
    for i in range(1, 9):
        core_labels[i]["status"].config(text="●", fg="gray")
        core_labels[i]["info"].config(text=f"Jádro {i}: Připraveno")
        core_labels[i]["states"].config(text="Stavy: 0")
        core_labels[i]["speed"].config(text="Rychlost: 0 st/s")


#                               -----AI-------
# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
def zrcadli(matice):
    return [radek[::-1] for radek in matice]


def rotuj_doprava(matice):
    return [list(radek) for radek in zip(*matice[::-1])]


def otoc_zpet(matice, uhel):
    nova = matice
    if uhel == 90:
        for _ in range(3): nova = rotuj_doprava(nova)
    elif uhel == 180:
        for _ in range(2): nova = rotuj_doprava(nova)
    elif uhel == 270:
        for _ in range(1): nova = rotuj_doprava(nova)
    return nova


def vnitrni_proces(uhel, zrcadlit_data, sudoku, queue, start_time, stop_flag, id_procesu):
    data = [radek[:] for radek in sudoku]

    if zrcadlit_data: data = zrcadli(data)
    if uhel == 90:
        data = rotuj_doprava(data)
    elif uhel == 180:
        data = rotuj_doprava(rotuj_doprava(data))
    elif uhel == 270:
        data = rotuj_doprava(rotuj_doprava(rotuj_doprava(data)))

    solver = SudokuSolver(data)

    # Signál do GUI, že jádro ožilo
    queue.put(("online", (id_procesu, uhel, zrcadlit_data)))

    reseni = solver.solve(stop_flag, queue, id_procesu)

    if reseni:
        temp_res = otoc_zpet(reseni, uhel)
        if zrcadlit_data: temp_res = zrcadli(temp_res)
        queue.put(("success", (temp_res, uhel, zrcadlit_data, time.time() - start_time)))
    else:
        # Signál, že jádro dokončilo práci bez nalezení výsledku
        queue.put(("dead", id_procesu))


#                           AI
# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

def solve(sudokug_list, root_window, core_labels, info_label):
    info_label.config(text="Počítám...", fg="black")
    sudoku = []
    for y in range(9):
        radek = []
        for x in range(9):
            hodnota = sudokug_list[y][x].get()
            if hodnota == "" or not hodnota.isdigit():
                radek.append(0)
            else:
                radek.append(int(hodnota))
        sudoku.append(radek)

    a = time.time()
    queue = multiprocessing.Queue()
    stop_flag = multiprocessing.Value('i', 0)
    procesy = []

    id_procesu = 1
    for zrcadlit in [False, True]:
        for uhel in [0, 90, 180, 270]:
            p = multiprocessing.Process(
                target=vnitrni_proces,
                args=(uhel, zrcadlit, sudoku, queue, a, stop_flag, id_procesu)
            )
            p.daemon = True
            p.start()
            procesy.append(p)
            id_procesu += 1

    def zkontroluj_semafor():
        while not queue.empty():
            msg_type, msg_data = queue.get()

            if msg_type == "online":
                idx, uhel, zrc = msg_data
                core_labels[idx]["status"].config(text="●", fg="green")
                core_labels[idx]["info"].config(text=f"Jádro {idx}: {uhel}° | Zrc: {zrc}")

            elif msg_type == "report":
                idx, krok, rychlost = msg_data
                core_labels[idx]["states"].config(text=f"Stavy: {krok:,}")
                core_labels[idx]["speed"].config(text=f"{rychlost:,.0f} st/s")


            elif msg_type == "dead":

                idx = msg_data

                core_labels[idx]["status"].config(text="●", fg="red")

                core_labels[idx]["speed"].config(text="Dokončeno")

                # --- OPRAVA: Jakmile jedno jádro stoprocentně projde celý strom a selže,

                # znamená to, že sudoku nemá řešení jako celek. Okamžitě vypínáme zbytek!

                stop_flag.value = 1

                for p in procesy:

                    if p.is_alive():
                        p.terminate()

                        p.kill()

                    p.join(timeout=0.1)

                queue.close()

                queue.join_thread()

                info_label.config(text=f"Sudoku NEMÁ řešení! (Dokázáno Jádrem {idx})", fg="red")


                for i in range(1, 9):

                    if core_labels[i]["status"].cget("fg") == "green":
                        core_labels[i]["status"].config(text="●", fg="orange")

                        core_labels[i]["speed"].config(text="Zastaveno")

                return
            elif msg_type == "success":
                finalni_sudoku, uhel, zrcadlit_data, celkovy_cas = msg_data
                stop_flag.value = 1

                for p in procesy:
                    if p.is_alive(): p.terminate(); p.kill()
                    p.join(timeout=0.1)

                queue.close()
                queue.join_thread()

                info_label.config(text=f"VYŘEŠENO! Úhel {uhel}°, čas: {celkovy_cas:.4f}s", fg="green")

                # Všechna zbývající živá jádra označíme jako zastavená externě
                for i in range(1, 9):
                    if core_labels[i]["status"].cget("fg") == "green":
                        core_labels[i]["status"].config(text="●", fg="orange")
                        core_labels[i]["speed"].config(text="Zastaveno")

                for y in range(9):
                    for x in range(9):
                        if sudokug_list[y][x].get() == "":
                            cislo = finalni_sudoku[y][x]
                            sudokug_list[y][x].insert(0, str(cislo))
                            sudokug_list[y][x].config(fg="blue")
                return

        ziji_procesy = any(p.is_alive() for p in procesy)
        if not ziji_procesy and queue.empty():
            info_label.config(text="Sudoku NEMÁ řešení!", fg="red")
            queue.close()
            queue.join_thread()
            return

        root_window.after(20, zkontroluj_semafor)

    zkontroluj_semafor()


if __name__ == '__main__':
    multiprocessing.freeze_support()

    root = tk.Tk()
    root.title("Řešič sudoku premium")
    root.geometry("460x680")

    grid_frame = tk.Frame(root)
    grid_frame.pack(side=tk.TOP, fill=tk.BOTH, expand=True, padx=10, pady=5)

    for i in range(9):
        grid_frame.columnconfigure(i, weight=1)
        grid_frame.rowconfigure(i, weight=1)

    sudokug = []
    for y in range(9):
        row = []
        for x in range(9):
            k = 5 if (x + 1) % 3 == 0 else 1
            k2 = 5 if (y + 1) % 3 == 0 else 1
            entry = tk.Entry(grid_frame, width=3, justify="center", font=("Arial", 16, "bold"))
            entry.grid(row=y, column=x, sticky="nsew", padx=(1, k), pady=(1, k2))
            row.append(entry)
        sudokug.append(row)

    info_lbl = tk.Label(root, text="Zadejte sudoku a stiskněte Vyřeš", font=("Arial", 11, "bold"))
    info_lbl.pack(pady=2)

    btn_frame = tk.Frame(root)
    btn_frame.pack(side=tk.TOP, fill=tk.X, padx=10, pady=2)

    # Vytvoření Dashboardu pro 8 jader
    dash_frame = tk.LabelFrame(root, text=" CPU Core Dashboard ", font=("Arial", 10, "bold"), padx=10,
                               pady=5)
    dash_frame.pack(side=tk.BOTTOM, fill=tk.BOTH, expand=True, padx=10, pady=10)

    core_widgets = {}
    for i in range(1, 9):
        row_f = tk.Frame(dash_frame)
        row_f.pack(fill=tk.X, pady=1)

        status_l = tk.Label(row_f, text="●", font=("Arial", 12), fg="gray", width=2)
        status_l.pack(side=tk.LEFT)

        info_l = tk.Label(row_f, text=f"Jádro {i}: Připraveno", font=("Courier", 9), width=24, anchor="w")
        info_l.pack(side=tk.LEFT)

        states_l = tk.Label(row_f, text="Stavy: 0", font=("Courier", 9), width=18, anchor="w")
        states_l.pack(side=tk.LEFT)

        speed_l = tk.Label(row_f, text="Rychlost: 0 st/s", font=("Courier", 9), width=16, anchor="e", fg="blue")
        speed_l.pack(side=tk.RIGHT)

        core_widgets[i] = {"status": status_l, "info": info_l, "states": states_l, "speed": speed_l}

    button = tk.Button(btn_frame, text="Vyřeš", command=lambda: solve(sudokug, root, core_widgets, info_lbl))
    button.pack(side=tk.LEFT, expand=True, fill=tk.X, padx=5)
    btn_reset = tk.Button(btn_frame, text="Reset", command=lambda: reset(sudokug, core_widgets))
    btn_reset.pack(side=tk.RIGHT, expand=True, fill=tk.X, padx=5)


    def on_closing():
        for p in multiprocessing.active_children(): p.terminate()
        root.destroy()


    root.protocol("WM_DELETE_WINDOW", on_closing)
    root.mainloop()
